import React from 'react';
import {
  BookOpenCheck,
  KeyRound,
  CreditCard,
  Briefcase,
  QrCode,
  Link2,
  AlertOctagon,
  PhoneCall,
  CheckCircle2,
  Shield,
  LifeBuoy,
} from 'lucide-react';

export const SecurityTips: React.FC = () => {
  const safetyCards = [
    {
      title: 'OTP Safety',
      quote: 'Never share OTPs with callers, messages, or unknown websites.',
      icon: KeyRound,
      color: 'border-red-500/40 text-red-400 bg-red-950/20',
      tips: [
        'Bank managers, police officers, and telecom executives will NEVER ask for your OTP.',
        'Read the SMS text carefully: does it say "OTP for transferring ₹5,000" instead of "login"?',
        'Never forward incoming SMS verification messages or install screen-sharing tools.',
      ],
    },
    {
      title: 'Payment Safety',
      quote: 'Verify payment requests through an independent official channel.',
      icon: CreditCard,
      color: 'border-orange-500/40 text-orange-400 bg-orange-950/20',
      tips: [
        'You NEVER need to enter a UPI PIN or password to receive a payment or refund.',
        'Beware of "Collect Requests" sent on PhonePe, Google Pay, or Paytm disguised as refunds.',
        'Do not trust payment receipts sent as screenshots on WhatsApp without checking your banking app balance.',
      ],
    },
    {
      title: 'Job Scam Safety',
      quote: 'Do not pay registration or processing fees to secure a job.',
      icon: Briefcase,
      color: 'border-amber-500/40 text-amber-400 bg-amber-950/20',
      tips: [
        'Legitimate companies never ask candidates to pay for laptops, IDs, training, or application fees.',
        'Be extremely skeptical of offers promising ₹3,000/day for liking YouTube videos or completing Telegram tasks.',
        'Verify recruiters through official company career pages and company domain email addresses.',
      ],
    },
    {
      title: 'QR Code Safety',
      quote: 'Treat unexpected QR codes as potentially risky.',
      icon: QrCode,
      color: 'border-cyan-500/40 text-cyan-400 bg-cyan-950/20',
      tips: [
        'Scanning a QR code is exclusively for SENDING money or opening a URL.',
        'Never scan a QR code received over chat to "verify your identity" or "collect cashback".',
        'Inspect the URL preview generated by your camera before proceeding.',
      ],
    },
    {
      title: 'Phishing Safety',
      quote: 'Do not click links simply because a message creates urgency.',
      icon: Link2,
      color: 'border-blue-500/40 text-blue-400 bg-blue-950/20',
      tips: [
        'Check the exact spelling of the domain (e.g. sbi-kyc.top is NOT the official bank website).',
        'Hover over or scan links with ScamShield Live before opening.',
        'Look out for artificial deadlines: "Account suspended in 2 hours", "KYC expires today".',
      ],
    },
    {
      title: 'Digital Arrest & Police Extortion Safety',
      quote: 'Law enforcement agencies never conduct "digital arrests" or demand online settlements.',
      icon: PhoneCall,
      color: 'border-purple-500/40 text-purple-400 bg-purple-950/20',
      tips: [
        'Neither CBI, ED, Police, nor Customs interrogate citizens or issue arrest warrants over Skype or WhatsApp.',
        'Never transfer "verification deposits" or liquid assets to supposedly clear your name.',
        'Hang up immediately and contact your local police station or dial 1930.',
      ],
    },
  ];

  return (
    <div className="space-y-8 max-w-5xl mx-auto">
      {/* Header */}
      <div>
        <div className="flex items-center gap-2 text-xs font-mono uppercase tracking-wider text-slate-400">
          <BookOpenCheck className="w-4 h-4 text-cyan-400" />
          <span>Defensive Playbook</span>
        </div>
        <h2 className="text-2xl font-bold text-white mt-1">Practical Security Guidance</h2>
        <p className="text-xs sm:text-sm text-slate-300 mt-1">
          Essential rules and red flags to protect yourself and family from modern social-engineering attacks.
        </p>
      </div>

      {/* Philosophy Callout Banner */}
      <div className="p-5 rounded-xl bg-gradient-to-r from-cyan-950/60 to-slate-900 border border-cyan-800/50 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="text-xs font-mono uppercase tracking-wider text-cyan-400 font-semibold">
            Core Cybersecurity Axiom
          </div>
          <div className="text-lg font-extrabold text-white mt-0.5">
            “STOP. SCAN. UNDERSTAND. THEN ACT.”
          </div>
          <p className="text-xs text-slate-300 mt-1 max-w-xl">
            Attackers rely on inducing haste, panic, or excitement. Taking 30 seconds to pause and scan breaks the attacker's psychological control.
          </p>
        </div>
        <div className="shrink-0">
          <div className="px-3.5 py-1.5 rounded-lg bg-cyan-900/60 border border-cyan-700/60 text-cyan-200 text-xs font-mono font-bold">
            Zero-Trust Protocol
          </div>
        </div>
      </div>

      {/* Safety Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {safetyCards.map((card, idx) => {
          const Icon = card.icon;
          return (
            <div
              key={idx}
              className={`p-6 rounded-xl border ${card.color} flex flex-col justify-between space-y-4`}
            >
              <div>
                <div className="flex items-center gap-3 mb-2">
                  <div className="p-2 rounded-lg bg-slate-900/80 border border-slate-800 text-inherit">
                    <Icon className="w-5 h-5" />
                  </div>
                  <h3 className="text-lg font-bold text-white">{card.title}</h3>
                </div>

                <div className="p-3 rounded-lg bg-slate-950/70 border border-slate-800/90 text-xs sm:text-sm font-semibold text-slate-200 italic mb-4">
                  “{card.quote}”
                </div>

                <ul className="space-y-2 text-xs sm:text-sm text-slate-300">
                  {card.tips.map((tip, tIdx) => (
                    <li key={tIdx} className="flex items-start gap-2">
                      <CheckCircle2 className="w-4 h-4 text-cyan-400 shrink-0 mt-0.5" />
                      <span>{tip}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          );
        })}
      </div>

      {/* Emergency Incident Response Guide */}
      <div className="p-6 rounded-xl bg-slate-900/90 border border-red-500/30 space-y-4">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-red-950 text-red-400 border border-red-800/40">
            <AlertOctagon className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-white">Emergency Response: If You Already Clicked or Shared Data</h3>
            <p className="text-xs text-slate-400">Follow these critical immediate steps within the first 10 minutes</p>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 pt-2 text-xs text-slate-300">
          <div className="p-4 rounded-lg bg-slate-950 border border-slate-800 space-y-1">
            <div className="font-bold text-red-400 text-sm font-mono">1. Freeze Accounts</div>
            <p className="leading-relaxed">
              Call your bank helpline immediately or use the official mobile app to lock your debit cards, credit cards, and freeze UPI transactions.
            </p>
          </div>

          <div className="p-4 rounded-lg bg-slate-950 border border-slate-800 space-y-1">
            <div className="font-bold text-amber-400 text-sm font-mono">2. Report to Cybercrime</div>
            <p className="leading-relaxed">
              Dial national cyber fraud helpline <strong>1930</strong> (in India) or visit <strong>cybercrime.gov.in</strong> immediately to intercept money transfers.
            </p>
          </div>

          <div className="p-4 rounded-lg bg-slate-950 border border-slate-800 space-y-1">
            <div className="font-bold text-cyan-400 text-sm font-mono">3. Reset Credentials</div>
            <p className="leading-relaxed">
              Immediately change your netbanking passwords, email passwords, and enable hardware or authenticator app 2FA from a separate clean device.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
